# Generated by Django 6.0.6 on 2026-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_time'], 'verbose_name': 'Dars jadvali', 'verbose_name_plural': 'Dars jadvallari'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='days_of_week',
            field=models.JSONField(default=list, verbose_name='Hafta kunlari'),
        ),
    ]
