# Generated by Django 6.0.6 on 2026-06-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_schedule_multiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mavzu/Nomi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Maksimal ball')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='academy.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Nazorat ishi',
                'verbose_name_plural': 'Nazorat ishlari',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Ball')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="O'rin")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='academy.student', verbose_name="O'quvchi")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academy.controltest', verbose_name='Nazorat ishi')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['rank', '-score'],
                'unique_together': {('test', 'student')},
            },
        ),
    ]
