# Generated by Django 6.0.6 on 2026-06-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_control_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(choices=[(1, "🥇 1-o'rin"), (2, "🥈 2-o'rin"), (3, "🥉 3-o'rin")], verbose_name="O'rin")),
                ('issued_date', models.DateField(verbose_name='Berilgan sana')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academy.student', verbose_name="O'quvchi")),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='academy.testresult', verbose_name='Test natijasi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-issued_date', 'rank'],
            },
        ),
    ]
