# Generated by Django 6.0.6 on 2026-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_birthdate_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Kechikish (daqiqa)'),
        ),
    ]
