# Generated by Django 6.0.6 on 2026-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_student_parent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bot Admin',
                'verbose_name_plural': 'Bot Adminlar',
            },
        ),
    ]
